#!/usr/bin/env bash

[ -d /opt/nvim-linux-x86_64 ] && { echo "Neovim already installed, skipping."; exit 0; }

curl -fsSL https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz -o /tmp/nvim.tar.gz
sudo rm -rf /opt/nvim-linux-x86_64
sudo tar -C /opt -xzf /tmp/nvim.tar.gz
