#!/usr/bin/env bash

gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

mkdir -p "$HOME/.config/xdg-desktop-portal"

grep -qF 'default=gtk;wlr' "$HOME/.config/xdg-desktop-portal/portals.conf" || {
    echo "[preferred]" >> "$HOME/.config/xdg-desktop-portal/portals.conf"
    echo "default=gtk;wlr" >> "$HOME/.config/xdg-desktop-portal/portals.conf"
}
