#!/usr/bin/env bash

grep -qF '/opt/nvim-linux-x86_64/bin' ~/.bashrc || {
    printf "\n" >> ~/.bashrc
    echo "# Neovim config" >> ~/.bashrc
    echo "export PATH=\"\$PATH:/opt/nvim-linux-x86_64/bin\"" >> ~/.bashrc
    echo "alias vim=nvim" >> ~/.bashrc
}
